#!/root/python/bin/python2.7 python

import optparse
import sys

import yaml

from metadata import get_metadata


def show_metadata():
    print yaml.dump(get_metadata(), default_flow_style=False)


def show_version():
    md = get_metadata()
    try:
        print '%s (version %s)' % (md['APP'],
                                   md['VERSION'])
    except KeyError:
        print 'no version info'


def show_docs():
    pass


def show_examples():
    pass


def show_usage():
    pass


def main():
    parser = optparse.OptionParser()
    parser.add_option('-v', '--version', dest='version',
                      action='store_true',
                      help='display version of the container')
    parser.add_option('-m', '--metadata', dest='metadata',
                      action='store_true',
                      help='display metadata')
    parser.add_option('-d', '--docs', dest='docs',
                      action='store_true',
                      help='display docs')
    parser.add_option('-e', '--examples', dest='examples',
                      action='store_true',
                      help='display examples')
    options, _ = parser.parse_args()
    if options.version:
        show_version()
        return 0
    if options.metadata:
        show_metadata()
        return 0
    if options.docs:
        show_docs()
        return 0
    if options.examples:
        show_examples()
        return 0
    show_usage()


if __name__ == '__main__':
    sys.exit(main())
