#!/usr/bin/env python

import optparse
import sys

import yaml

from metadata import get_metadata


def show_all():
    print yaml.dump(get_metadata(), default_flow_style=False)


def show_docs():
    pass


def main():
    parser = optparse.OptionParser()
    parser.add_option('-v', '--version', dest='version',
                      action='store_true',
                      help='display version of the container')
    parser.add_option('-m', '--metadata', dest='metadata',
                      action='store_true',
                      help='display metadata')
    parser.add_option('-d', '--docs', dest='docs',
                      action='store_true',
                      help='display docs')
    parser.add_option('-e', '--examples', dest='examples',
                      action='store_true',
                      help='display examples')
    options, _ = parser.parse_args()
    if options.version:
        md = get_metadata()
        try:
            print '%s (version %s)' % (md['NAME'],
                                       md['VERSION'])
        except KeyError:
            print 'no version info'
        return 0
    show_docs()


if __name__ == '__main__':
    sys.exit(main())
