#!/root/python/bin/python2.7 python

import optparse
import sys

from blessings import Terminal
import yaml

import metadata


t = Terminal()


def show_metadata():
    for k, v in metadata.get_metadata().items():
        print('{t.green}{k}: {t.cyan}{v}{t.normal}'
              .format(t=t, k=k, v=v))


def show_version():
    md = metadata.get_metadata()
    try:
        print '%s (version %s)' % (md['APP'],
                                   md['VERSION'])
    except KeyError:
        print t.red('no version info')


def show_text(kind='intro', title='Docs'):
    for filename, image in metadata.get_files(kind=kind):
        title_len = len('{title} for {image}:'
                        .format(title=title, image=image))
        print ('{t.bright_green}{line}{t.normal}\n'
               '{t.bright_green}{title} for '
               '{t.bright_cyan}{image}{t.bright_green}:{t.normal}'
               '\n{t.bright_green}{line}{t.normal}'
               .format(t=t, image=image, title=title, line='-'*title_len))
        print(open(filename).read())


def show_docs():
    show_text()


def show_examples():
    show_text('examples', 'Examples')


def show_usage():
    show_text('usage', 'Usage')


def main():
    parser = optparse.OptionParser()
    parser.add_option('-v', '--version', dest='version',
                      action='store_true',
                      help='display version of the container')
    parser.add_option('-m', '--metadata', dest='metadata',
                      action='store_true',
                      help='display metadata')
    parser.add_option('-d', '--docs', dest='docs',
                      action='store_true',
                      help='display docs')
    parser.add_option('-e', '--examples', dest='examples',
                      action='store_true',
                      help='display examples')
    options, _ = parser.parse_args()
    if options.version:
        show_version()
        return 0
    if options.metadata:
        show_metadata()
        return 0
    if options.docs:
        show_docs()
        return 0
    if options.examples:
        show_examples()
        return 0
    show_usage()


if __name__ == '__main__':
    sys.exit(main())
